### ISSUE TITLE
Heap alloc on every frame?

### ISSUE THREAD

**Issue by toastmod** [Blatko1/wgpu-text#37]
Hey there, this crate looks fantastic but I have one gripe with this line of code in the example.
```rust
brush.queue(&device, &queue, vec![&section, ...]).unwrap();
```
The `vec!` here is a heap allocation on every frame. The `Vec` isn't a reference so the function takes ownership of the `Vec`, therefore you can't `clear`/`extend` the existing allocation, it just gets dropped and the OS has to deallocate it. After that `vec!` is called again and a brand new allocation has to be made and written to. Performance might be okay but I'm curious why it's written this way, I wouldn't think this is the most ideal as this could scale up to be a problem or vary in performance across OS's.

I am willing to contribute a change if necessary, but if there is a reason it's written this way I'd like to know :)

Thanks!

**Comment by Blatko1** [comment]
Thank you for looking into this crate! I didn't think much of it when I made that function because I thought vectors would always be small in capacity, but now I see that it could be a problem. So, the best solution would probably be to ask for a reference to a slice. Would you agree? I could also split the function into one that takes only one reference to a section as an argument and another that takes a reference to a slice of referenced sections. You can create a pull request if you want.

**Comment by Blatko1** [comment]
I think the above commit fixes the heap allocation on every frame. I copied part of the function from **wgpu** `Queue::submit(&self, command_buffers: IntoIterator<Item = CommandBuffer>)` and placed it in the `Brush::queue()` function. Now you can just pass a static array.
