### ISSUE TITLE
How to find a glyph size in px?

### ISSUE THREAD

**Issue by kakoc** [Blatko1/wgpu-text#9]
Hi, thanks for your crate!  
After some tinkering I can't find how can I find glyph sizes(width, height) in px  
Can you suggest how can I do that?

**Comment by Blatko1** [comment]
Since this project is a wrapper over the **glyph_brush** crate, most features and objects are reimplemented from there. Look into the **[Font](https://docs.rs/glyph_brush/latest/glyph_brush/ab_glyph/trait.Font.html#provided-methods)** trait, which contains a couple of useful glyph functions. One of the functions is [outline_glyph()](https://docs.rs/glyph_brush/latest/glyph_brush/ab_glyph/trait.Font.html#method.outline_glyph), which takes a **[Glyph](https://docs.rs/glyph_brush/latest/glyph_brush/ab_glyph/struct.Glyph.html)** as input and returns an **[OutlinedGlyph](https://docs.rs/glyph_brush/latest/glyph_brush/ab_glyph/struct.OutlinedGlyph.html)** with all necessary bounding and outline information.
> The following is currently (v0.6.7) not possible but will be when v0.7.0 releases

Here is a short code example:
```rust
let brush: TextBrush = /*BrushBuilder here*/;
let mut section = Section::default()
    .add_text(Text::new("short text"))
    .to_owned();
let font = &brush.fonts()[0].clone();
let mut iter = brush.glyphs_iter(&section);
println!(
    "glyph info: {:?}",
    font.outline_glyph(iter.next().unwrap().glyph.clone())
);
```
The **glyphs_iter()** function returns an iterator over all positioned glyphs in the **Section**.
This method is the first one I have found, so it may not be the best, but you can try browsing the [glyph_brush](https://docs.rs/glyph_brush/latest/glyph_brush/index.html) crate for a better solution.
I know that this currently isn't possible but will be when v0.7.0 releases.
